language: php

php: 
  - 7.3
  - 7.4
  - 8.0

services:
 - mysql

before_script: 
  - composer install
  - mysql -e "CREATE DATABASE IF NOT EXISTS phluent_test;"

script: 
  - composer run-script test-query
  

after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --coverage_clover=build/logs/clover.xml -v

notifications:
  email: "me@indgy.uk"