language: php

php: 
  - 7.3
  - 7.4
  - 8.0

# services:
#  - mysql

before_script: composer install

script: phpunit --coverage-text --configuration phpunit.xml

notifications:
  email: "me@indgy.uk"
